# Generated by Django 6.1.1 on 2026-09-20 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listingimage_image_and_more'),
        ('statistics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['listing', 'user', 'created_at'], name='listing_view_user_index'),
        ),
        migrations.AddIndex(
            model_name='searchquery',
            index=models.Index(fields=['keyword'], name='search_query_keyword_index'),
        ),
    ]
