# Generated by Django 6.1.1 on 2026-09-16 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='max_guests',
            field=models.PositiveIntegerField(default=1, verbose_name='Max guests'),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_guests',
            field=models.PositiveIntegerField(default=1, verbose_name='Max guests'),
        ),
        migrations.CreateModel(
            name='BlockedDateRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='listings.listing', verbose_name='Listing')),
            ],
            options={
                'verbose_name': 'Blocked date range',
                'verbose_name_plural': 'Blocked date ranges',
                'db_table': 'listing_blocked_dates',
                'ordering': ('-start_date',),
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='blocked_range_end_date_after_start_date')],
            },
        ),
    ]
