# Generated by Django 6.1.1 on 2026-09-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_historicallisting_max_guests_listing_max_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallisting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
    ]
