# Generated by Django 6.1.1 on 2026-09-20 09:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_historicallisting_deleted_at_listing_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='listings/photos', verbose_name='Image'),
        ),
        migrations.AddIndex(
            model_name='blockeddaterange',
            index=models.Index(fields=['listing', 'start_date', 'end_date'], name='blocked_range_overlap_index'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('rooms_count__gte', 1)), name='listing_rooms_count_at_least_1'),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(('max_guests__gte', 1)), name='listing_max_guests_at_least_1'),
        ),
    ]
