# Generated by Django 6.1.1 on 2026-09-20 09:39

import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_guests_count_historicalbooking_guests_count_and_more'),
        ('listings', '0005_alter_listingimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', editable=False, help_text="Snapshot of listing.price * nights at the time the booking was made doesn't change if the listing's price changes later", max_digits=10, null=True, verbose_name='Total price'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='total_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', editable=False, help_text="Snapshot of listing.price * nights at the time the booking was made doesn't change if the listing's price changes later", max_digits=10, null=True, verbose_name='Total price'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'status', 'start_date', 'end_date'], name='booking_overlap_index'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='booking_status_created_index'),
        ),
    ]
